#!/usr/bin/env python3
"""
Towers of Atheria - stamp packer for the browser bench.

The source stamps are 1920x1080 RGBA files, ~1 MB each, because the artwork
is a small shape floating on a huge transparent canvas. This crops each one
to its actual pixels, scales it to icon size, and base64-embeds the lot into
index.html so the game stays ONE self-contained file.

Same discipline as build_catalog.py: generated, never hand-edited, so the
icons in the bench are literally the same art that prints on the cards.
Players learn to read the real stamps while they play, which is the whole
point of using the bench as a teaching and advertising tool.

    python3 build_stamps.py     ->  injects into index.html
"""
import base64, io, os, re, sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required:  pip install pillow")

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "stamps")
PX = 72          # rendered at 18-30px, so 72 covers retina without bloat

# key used in the JS  ->  source filename
WANTED = {
    "t1": "T1Stamp.png", "t2": "T2Stamp.png", "t3": "T3Stamp.png", "t4": "T4Stamp.png",
    "dungeon": "DungeonDwellerStamp'.png",
    "lava":    "LavaDwellerStamp.png",
    "honor":   "HonorDwellerStamp.png",
    "forest":  "ForestDwellerStamp.png",
    "sea":     "SeaDwellerStamp.png",
    "earth":   "EarthDwellerStamp.png",
    "melee":   "SwordStamp.png",
    "ranged":  "ArrowStamp.png",
    "movable":   "WalkingIcon.png",
    "immovable": "NonWalkingIcon.png",
}


def pack(path):
    """Crop to the real artwork, square it, scale down, return PNG bytes."""
    im = Image.open(path).convert("RGBA")
    bb = im.getchannel("A").getbbox()
    if bb:
        im = im.crop(bb)
    # pad to a square so nothing distorts when the CSS forces equal width/height
    w, h = im.size
    side = max(w, h)
    sq = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    sq.paste(im, ((side - w) // 2, (side - h) // 2))
    sq = sq.resize((PX, PX), Image.LANCZOS)
    buf = io.BytesIO()
    sq.save(buf, "PNG", optimize=True)
    return buf.getvalue()


def main():
    if not os.path.isdir(SRC):
        sys.exit(f"stamps folder not found: {SRC}")

    out, total, missing = {}, 0, []
    for key, fn in WANTED.items():
        p = os.path.join(SRC, fn)
        if not os.path.exists(p):
            missing.append(f"{key} -> {fn}")
            continue
        data = pack(p)
        total += len(data)
        out[key] = "data:image/png;base64," + base64.b64encode(data).decode()
        print(f"  {key:<10} {os.path.getsize(p)//1024:>5} KB  ->  {len(data)/1024:>5.1f} KB")

    for m in missing:
        print(f"  !! MISSING {m}", file=sys.stderr)

    payload = ('<script id="stamps">/* GENERATED by build_stamps.py - do not edit */\n'
               "window.TOA_STAMPS={" +
               ",".join(f'"{k}":"{v}"' for k, v in out.items()) +
               "};\n</script>")

    idx = os.path.join(HERE, "index.html")
    html = open(idx, encoding="utf-8").read()
    new, n = re.subn(r'<script id="stamps">.*?</script>', payload, html, flags=re.S)
    if not n:
        sys.exit('index.html has no <script id="stamps"> marker to replace')
    open(idx, "w", encoding="utf-8").write(new)

    print(f"\n  {len(out)} stamps packed: {total/1024:.0f} KB raw, "
          f"{len(payload)/1024:.0f} KB as base64 in index.html")
    print(f"  (source files were {sum(os.path.getsize(os.path.join(SRC, f)) for f in WANTED.values() if os.path.exists(os.path.join(SRC, f)))//1024//1024} MB)")


if __name__ == "__main__":
    main()
